### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] - Windows Server 2022.

### ISSUE THREAD

**Issue by DrazekIronwing** [BigChicChicken/NW_TimerBot#8]
I've installed the NW_TimerBot on a new windows 2022 server, following the tutorial (I've already had this working fine on a 2019 server).

however now i'm getting the following error, and i'm not sure how to fix it?

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at new ReadStream (node:internal/fs/streams:171:5)
    at Object.createReadStream (node:fs:2963:10)
    at TimerBot.playAudio (file:///C:/Servers/NW_TimerBot/src/TimerBot.js:66:53)
    at Timeout._onTimeout (file:///C:/Servers/NW_TimerBot/src/TimerBot.js:156:34)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by BigChicChicken** [comment]
Hi, your problem comes from reading the file.
I can only advise you to check the rights on the files under the folder "/src/resources/" ...
